package com.example.flightsapp.ui.theme

import androidx.compose.ui.graphics.Color


// Light theme colors
val md_theme_light_primary = Color(0xFF3A7CA5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD0E7F5)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2E)
val md_theme_light_secondary = Color(0xFF5B7083)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E2EA)
val md_theme_light_onSecondaryContainer = Color(0xFF121E27)
val md_theme_light_tertiary = Color(0xFF6D8EA0)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCEE4F0)
val md_theme_light_onTertiaryContainer = Color(0xFF0E2A38)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FBFD)
val md_theme_light_onBackground = Color(0xFF1C1F21)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C1F21)
val md_theme_light_surfaceVariant = Color(0xFFE0E6EC)
val md_theme_light_onSurfaceVariant = Color(0xFF444A50)
val md_theme_light_outline = Color(0xFF7A8A97)
val md_theme_light_inverseOnSurface = Color(0xFFF0F3F5)
val md_theme_light_inverseSurface = Color(0xFF2E3942)
val md_theme_light_inversePrimary = Color(0xFF9CCAFF)
val md_theme_light_surfaceTint = md_theme_light_primary
val md_theme_light_scrim = Color(0xFF000000)

// Dark theme colors
val md_theme_dark_primary = Color(0xFF9CCAFF)
val md_theme_dark_onPrimary = Color(0xFF00344D)
val md_theme_dark_primaryContainer = Color(0xFF004D6B)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0E7F5)
val md_theme_dark_secondary = Color(0xFFBDC7D2)
val md_theme_dark_onSecondary = Color(0xFF27333D)
val md_theme_dark_secondaryContainer = Color(0xFF3E4B55)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E2EA)
val md_theme_dark_tertiary = Color(0xFFC0D9E6)
val md_theme_dark_onTertiary = Color(0xFF243944)
val md_theme_dark_tertiaryContainer = Color(0xFF3C5160)
val md_theme_dark_onTertiaryContainer = Color(0xFFCEE4F0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF121C24)
val md_theme_dark_onBackground = Color(0xFFE0E6EC)
val md_theme_dark_surface = Color(0xFF18232C)
val md_theme_dark_onSurface = Color(0xFFE0E6EC)
val md_theme_dark_surfaceVariant = Color(0xFF404A52)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8D1)
val md_theme_dark_outline = Color(0xFF8A98A3)
val md_theme_dark_inverseOnSurface = Color(0xFF121C24)
val md_theme_dark_inverseSurface = Color(0xFFE0E6EC)
val md_theme_dark_inversePrimary = Color(0xFF3A7CA5)
val md_theme_dark_surfaceTint = md_theme_dark_primary
val md_theme_dark_scrim = Color(0xFF000000)