package com.example.flightsapp.Common

//Fake flight data, to bee displayed and used on the application
//The data was generated by chatGDP

object FlightsRepository {

    val flights = listOf(
        Flights(8.30, 10.45, 2.25, "JFK", "YYZ", "Air Canada", 120, true, 180.0),
        Flights(9.00, 12.20, 3.20, "LAX", "DEN", "United Airlines", 85, true, 150.0),
        Flights(7.15, 11.45, 4.30, "ORD", "MIA", "American Airlines", 60, true, 210.0),
        Flights(6.50, 9.10, 2.20, "SFO", "SEA", "Alaska Airlines", 90, true, 120.0),
        Flights(10.00, 14.30, 4.50, "JFK", "LAX", "Delta", 40, true, 320.0),

        Flights(5.40, 8.10, 2.30, "CDG", "FCO", "Air France", 75, true, 140.0),
        Flights(12.00, 14.15, 2.15, "LHR", "AMS", "British Airways", 110, true, 160.0),
        Flights(15.30, 18.45, 3.15, "MAD", "BER", "Iberia", 95, true, 175.0),
        Flights(9.10, 13.40, 4.30, "LHR", "ATH", "Aegean", 50, true, 220.0),
        Flights(6.00, 9.50, 3.50, "FRA", "LIS", "Lufthansa", 65, true, 200.0),

        Flights(11.30, 20.10, 8.40, "JFK", "LHR", "Virgin Atlantic", 35, true, 540.0),
        Flights(13.45, 22.30, 8.45, "BOS", "CDG", "Air France", 28, true, 510.0),
        Flights(16.20, 1.05, 8.45, "YYZ", "DUB", "Aer Lingus", 42, true, 480.0),
        Flights(19.00, 6.30, 11.50, "LAX", "LHR", "British Airways", 30, true, 650.0),
        Flights(22.10, 9.00, 10.50, "SFO", "FRA", "Lufthansa", 25, true, 670.0),

        Flights(7.00, 10.30, 3.30, "DXB", "RUH", "Emirates", 140, true, 190.0),
        Flights(14.15, 20.00, 5.45, "DXB", "IST", "Turkish Airlines", 100, true, 260.0),
        Flights(9.40, 18.10, 8.30, "DEL", "DXB", "IndiGo", 115, true, 310.0),
        Flights(23.00, 7.45, 8.45, "BOM", "LHR", "Vistara", 50, true, 560.0),
        Flights(6.20, 11.50, 5.30, "CAI", "CDG", "EgyptAir", 70, true, 340.0),

        Flights(8.10, 12.00, 3.50, "HND", "ICN", "ANA", 130, true, 220.0),
        Flights(10.30, 14.50, 4.20, "NRT", "HKG", "Cathay Pacific", 90, true, 280.0),
        Flights(22.00, 6.30, 8.30, "HND", "SYD", "Qantas", 40, true, 720.0),
        Flights(15.45, 19.30, 3.45, "ICN", "PEK", "Korean Air", 85, true, 260.0),
        Flights(7.25, 9.10, 1.45, "SIN", "KUL", "Singapore Airlines", 150, true, 110.0),

        Flights(9.00, 13.50, 4.50, "GRU", "SCL", "LATAM", 95, true, 300.0),
        Flights(14.40, 19.10, 4.30, "EZE", "LIM", "Aerolineas Argentinas", 70, true, 280.0),
        Flights(6.30, 11.20, 4.50, "BOG", "MEX", "Avianca", 88, true, 260.0),
        Flights(22.15, 6.45, 8.30, "GRU", "MAD", "Iberia", 45, true, 580.0),
        Flights(11.50, 14.10, 2.20, "SCL", "LIM", "Sky Airline", 110, true, 140.0),

        Flights(5.55, 7.45, 1.50, "SYD", "MEL", "Jetstar", 160, true, 90.0),
        Flights(13.10, 18.40, 5.30, "AKL", "SYD", "Air New Zealand", 80, true, 260.0),
        Flights(20.00, 6.20, 10.20, "SYD", "HND", "Qantas", 38, true, 740.0),
        Flights(7.40, 12.30, 4.50, "BNE", "PER", "Virgin Australia", 95, true, 310.0),
        Flights(16.00, 18.15, 2.15, "MEL", "ADL", "Rex Airlines", 120, true, 130.0),

        Flights(9.30, 12.00, 2.30, "CPH", "OSL", "SAS", 105, true, 150.0),
        Flights(15.45, 18.10, 2.25, "ARN", "HEL", "Finnair", 98, true, 160.0),
        Flights(6.20, 10.50, 4.30, "OSL", "ROM", "Norwegian", 75, true, 210.0),
        Flights(11.10, 14.40, 3.30, "ZRH", "BCN", "Swiss", 68, true, 195.0),
        Flights(18.00, 22.15, 4.15, "VIE", "IST", "Austrian Airlines", 82, true, 230.0)
    )
}

